// packages/client-chrome-extension/src/home/Home.tsx
import HomeHeader from '../components/HomeHeader';
import List from '../components/List';
import Bottom from '../components/Bottom';
import Footer from '../components/Footer';

function Home() {
    const params = {
        page: 1,
        size: 20,
    };
    return (
        <div className="Home">
            <HomeHeader />
            <List pageType="home" params={params} />
            <Bottom />
            <Footer />
        </div>
    );
}

export default Home;

// packages/client-chrome-extension/src/home/pages/Home.vue
<template>
    <home-header />
    <home-mainer />
    <home-footer />
    <router-view />
</template>

<script setup lang="ts">
import HomeHeader from '../components/HomeHeader.vue';
import HomeMainer from '../components/HomeMainer.vue';
import HomeFooter from '../components/HomeFooter.vue';
</script>
